export const valuesMap = {
    Appreciation: {
        Love: 1,
        Like: 2,
        Fine: 3,
        Dislike: 4,
        Hate: 5,
    },
    'Course Difficulty': {
        'Very Easy': 1,
        Easy: 2,
        Moderate: 3,
        Difficult: 4,
        'Very Difficult': 5,
    },
    'Final Difficulty': {
        'Very Easy': 1,
        Easy: 2,
        Moderate: 3,
        Difficult: 4,
        'Very Difficult': 5,
    },
    'Midterm Difficulty': {
        'Very Easy': 1,
        Easy: 2,
        Moderate: 3,
        Difficult: 4,
        'Very Difficult': 5,
    },
    Time: {
        '0-2': 1, // very good
        '2-4': 2,
        '4-6': 3,
        '6-8': 4,
        '8-10': 5,
        '10+': 6,
    },
    Interest: {
        'Very Interesting': 1,
        Interesting: 2,
        Fine: 3,
        Boring: 4,
        'Very Boring': 5,
    },
    Quality: {
        'Very Good': 1,
        Good: 2,
        Normal: 3,
        Poor: 4,
        'Very Poor': 5,
    },
    Learning: {
        'A Lot': 1,
        'A Good Amount': 2,
        'A Little': 3,
        Nothing: 4,
    },
    'Self-Learning': {
        'Totally sufficient': 1,
        'Mostly sufficient': 2,
        'Just sufficient': 3,
        'Hardly sufficient': 4,
        'Not at all': 5,
    },
};
