const modules = {
    "Level 4": {
        CM: {
            name: "Computational Mathematics",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: true,
            slack: "",
            repl: "",
            rpl: "",
        },
        DM: {
            name: "Discrete Mathematics",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: true,
            slack: "",
            repl: "",
            rpl: "",
        },
        FCS: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: false,
            slack: "",
            repl: "",
            rpl: "",
        },
        ITP1: {
            name: "Introduction to Programming I",
            code: "CM1005",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: true,
            slack: "https://app.slack.com/client/TDT1N1BUG/CH35RKXK8",
            repl: "",
            rpl: "",
        },
        ITP2: {
            name: "Introduction to Programming II",
            code: "",
            syllabus:
                "https://github.com/world-class/binary-assets/blob/master/modules/syllabi/Syllabus_CM1010_ITP2.pdf",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: true,
            slack: "",
            repl: "",
            rpl: "",
        },
        ADS1: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        WD: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        HCW: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
    },
    "Level 5": {
        OOP: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        SDD: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        CSec: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        ASP: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        ADS2: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        GP: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        DNW: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        PWD: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
    },
    "Level 6": {
        FP: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        ISP: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        NLP: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        ID: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        MD: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        "3DG": {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        IoT: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        AWD: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        GD: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
        VR: {
            name: "",
            code: "",
            syllabus: "",
            specification: "",
            languages: "",
            professor: "",
            midterm: "",
            final: "",
            blocker: "",
            slack: "",
            repl: "",
            rpl: "",
        },
    },
};

const getModulesForLevel = levelName => {
    const modulesByLevel = modules[levelName];
    if (!modulesByLevel) {
        return [];
    }
    return Object.keys(modulesByLevel);
};

export { modules, getModulesForLevel };
